### ISSUE TITLE
SAMU performance

### ISSUE THREAD

**Issue by midenok** [midenok/mariadb#110]
```
[root@snsvr01 samu38_repro]# ./mp -S10.4.20 -G && ./mp -S10.2 -G
! Using mariadb-10.4.20samurai
! Started: 146175
Rows in samu38: 10000000 (100%)
! Stopped: 146175
* Server dirty stats:
data: 0  faults: 0  rfaults: 2277939  fsi: 0  fso: 54824112  socki: 0  socko: 0  mem: 0  rss_avg: 0  rss_max: 252436  shared: 0  stack: 0  cpu: 208  sys: 73.74  usr: 2511.70  real: 1241.48  swaps: 0  ctx0: 31523  ctx1: 10015816  sigs: 0  ret: 0
! Using mariadb-10.10.2
! Started: 183481
Rows in samu38: 10000000 (100%)
! Stopped: 183481
* Server dirty stats:
data: 0  faults: 0  rfaults: 889579  fsi: 3611306  fso: 5775373  socki: 0  socko: 0  mem: 0  rss_avg: 0  rss_max: 362684  shared: 0  stack: 0  cpu: 45  sys: 38.49  usr: 445.69  real: 1064.60  swaps: 0  ctx0: 96843  ctx1: 7953498  sigs: 0  ret: 0
```

**Comment by midenok** [comment]
* https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/Optimize-Options.html#Optimize-Options
* 
#### -fprofile-correction
Profiles collected using an instrumented binary for multi-threaded programs may be inconsistent due to missed counter updates. When this option is specified, GCC uses heuristics to correct or smooth out such inconsistencies. By default, GCC emits an error message when an inconsistent profile is detected.

#### -fprofile-dir=path
Set the directory to search for the profile data files in to path. This option affects only the profile data generated by -fprofile-generate, -ftest-coverage, -fprofile-arcs and used by -fprofile-use and -fbranch-probabilities and its related options. Both absolute and relative paths can be used. By default, GCC uses the current directory as path, thus the profile data file appears in the same directory as the object file.

#### -fprofile-generate
#### -fprofile-generate=path
Enable options usually used for instrumenting application to produce profile useful for later recompilation with profile feedback based optimization. You must use -fprofile-generate both when compiling and when linking your program.
The following options are enabled: -fprofile-arcs, -fprofile-values, -fvpt.

If path is specified, GCC looks at the path to find the profile feedback data files. See -fprofile-dir.

#### -fprofile-use
#### -fprofile-use=path
Enable profile feedback directed optimizations, and optimizations generally profitable only with profile feedback available.
The following options are enabled: -fbranch-probabilities, -fvpt, -funroll-loops, -fpeel-loops, -ftracer, -ftree-vectorize, ftree-loop-distribute-patterns

By default, GCC emits an error message if the feedback profiles do not match the source code. This error can be turned into a warning by using -Wcoverage-mismatch. Note this may result in poorly optimized code.

If path is specified, GCC looks at the path to find the profile feedback data files. See -fprofile-dir.

#### -freorder-functions
Reorder functions in the object file in order to improve code locality. This is implemented by using special subsections .text.hot for most frequently executed functions and .text.unlikely for unlikely executed functions. Reordering is done by the linker so object file format must support named sections and linker must place them in a reasonable way.

This option isn’t effective unless you either provide profile feedback (see -fprofile-arcs for details) or manually annotate functions with hot or cold attributes (see [Common Function Attributes](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes)).

Enabled at levels -O2, -O3, -Os.

#### More
https://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Function-Attributes.html

* aligned (alignment)
* -falign-functions

https://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Optimize-Options.html#Optimize-Options
* -flto[=n]

**Comment by midenok** [comment]
### Links
* https://mariadbcorp.atlassian.net/browse/SAMU-90

#### Build options from ServiceNow
```
cmake -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_C_FLAGS_RELEASE:STRING='-g -O3 -Wl,-z,relro,-z,now' \
            -DCMAKE_CXX_FLAGS_RELEASE:STRING='-g -O3 -Wl,-z,relro,-z,now' \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON \
            -DWITH_DBUG_TRACE:BOOL=OFF \
            -DMAX_INDEXES:STRING=128 \
            -DWITH_PCRE:STRING=bundled \
            -DWITH_WSREP:BOOL=OFF \
            -DPLUGIN_CONNECT:STRING=NO \
            -DPLUGIN_SPIDER:STRING=NO \
            -DPLUGIN_ROCKSDB:STRING=NO \
            -DPLUGIN_TOKUDB:STRING=NO \
            -DPLUGIN_MROONGA:STRING=NO \
            -DPLUGIN_ARCHIVE:STRING=NO \
            -DPLUGIN_SPHINX:STRING=NO \
            -DPLUGIN_AUTH_PAM:STRING=NO \
            -DPLUGIN_AUTH_GSSAPI:STRING=NO \
            -DWITH_INNODB_LZMA:BOOL=OFF .
```
#### Other options
```
            -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc \
            -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ \
            -DCMAKE_INSTALL_PREFIX:PATH=/glide/samurai/%{version} \
```
#### My options
```
        -DSECURITY_HARDENED:BOOL=FALSE \
        -DMYSQL_MAINTAINER_MODE:STRING=OFF \
        -DUPDATE_SUBMODULES:BOOL=OFF \
        -DPLUGIN_METADATA_LOCK_INFO:STRING=STATIC \
        -DWITH_UNIT_TESTS:BOOL=OFF \
        -DWITH_CSV_STORAGE_ENGINE:BOOL=OFF \
        -DWITH_WSREP:BOOL=OFF \
        -DWITH_MARIABACKUP:BOOL=OFF \
        -DWITH_SAFEMALLOC:BOOL=OFF \
```
#### ServiceNow binaries
```
/ten1/10.4.20samurai is running now the mysqld_10.4.20samurai1.0
```

**Comment by midenok** [comment]
### From SNOW binary
```
  cb7a90:       e8 bb c6 e6 ff          call   b24150 <rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)>
  cb8201:       e8 4a bf e6 ff          call   b24150 <rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)>
  cb8261:       e8 ea be e6 ff          call   b24150 <rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)>
  cb841c:       e8 2f bd e6 ff          call   b24150 <rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)>
  cb8f1d:       e8 2e b2 e6 ff          call   b24150 <rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)>
  cb8f81:       e8 ca b1 e6 ff          call   b24150 <rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)>
  cb913c:       e8 0f b0 e6 ff          call   b24150 <rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)>
```
```
$ grep rec_get_offsets_func 1.asm|wc -l
349
```

**Comment by midenok** [comment]
### Stack used 85%
```c++
#0  rec_get_offsets_func (rec=rec@entry=0x7fa09669f1c9 "", index=index@entry=0x557dfa1d1148, offsets=0x557dfa44f158, n_core=1003, n_fields=n_fields@entry=18446744073709551615, heap=heap@entry=0x7fa0ac0759f0) at /home/midenok/src/mariadb/10.4/src/storage/innobase/rem/rem0rec.cc:822
#1  0x0000557df716bacd in row_search_mvcc (buf=buf@entry=0x557dfa0ff600 "\001c410", mode=PAGE_CUR_G, mode@entry=PAGE_CUR_UNSUPP, prebuilt=0x557dfa14a638, match_mode=match_mode@entry=0, direction=direction@entry=1) at /home/midenok/src/mariadb/10.4/src/storage/innobase/row/row0sel.cc:4938
#2  0x0000557df70a2657 in general_fetch (match_mode=0, direction=1, buf=0x557dfa0ff600 "\001c410", this=0x557dfa0cb730) at /home/midenok/src/mariadb/10.4/src/storage/innobase/handler/ha_innodb.cc:9627
#3  ha_innobase::rnd_next (this=0x557dfa0cb730, buf=0x557dfa0ff600 "\001c410") at /home/midenok/src/mariadb/10.4/src/storage/innobase/handler/ha_innodb.cc:9836
#4  0x0000557df6e51809 in handler::ha_rnd_next (this=this@entry=0x557dfa0cb730, buf=0x557dfa0ff600 "\001c410") at /home/midenok/src/mariadb/10.4/src/sql/handler.cc:2868
#5  0x0000557df6e4c71b in find_all_keys (found_rows=0x557dfa16b770, pq=0x7fa0ac076c20, tempfile=0x7fa0ac076d00, buffpek_pointers=0x7fa0ac076df0, fs_info=0x557dfa16b610, select=0x557dfa1b58f0, param=0x7fa0ac076c70, thd=0x557df9be7988) at /home/midenok/src/mariadb/10.4/src/sql/filesort.cc:774
#6  filesort (thd=thd@entry=0x557df9be7988, table=table@entry=0x557dfa0e62a8, filesort=filesort@entry=0x557dfa1b5a58, tracker=0x557dfa1b6110, join=join@entry=0x557dfa1b3d38, first_table_bit=<optimized out>) at /home/midenok/src/mariadb/10.4/src/sql/filesort.cc:268
#7  0x0000557df6cb03c8 in create_sort_index (thd=0x557df9be7988, join=0x557dfa1b3d38, tab=tab@entry=0x557dfa1b4fd8, fsort=0x557dfa1b5a58, fsort@entry=0x0) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:23868
#8  0x0000557df6cb06a6 in st_join_table::sort_table (this=this@entry=0x557dfa1b4fd8) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:21583
#9  0x0000557df6cb06fc in join_init_read_record (tab=0x557dfa1b4fd8) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:21522
#10 0x0000557df6ca7be1 in sub_select (join=0x557dfa1b3d38, join_tab=0x557dfa1b4fd8, end_of_records=<optimized out>) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:20599
#11 0x0000557df6cd51ac in do_select (procedure=0x0, join=0x557dfa1b3d38) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:20140
#12 JOIN::exec_inner (this=this@entry=0x557dfa1b3d38) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:4525
#13 0x0000557df6cd5484 in JOIN::exec (this=this@entry=0x557dfa1b3d38) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:4307
#14 0x0000557df6cd3730 in mysql_select (thd=thd@entry=0x557df9be7988, tables=0x557dfa1b2b10, wild_num=0, fields=..., conds=<optimized out>, og_num=1, order=0x557dfa1b3b30, group=0x0, having=0x0, proc_param=0x0, select_options=2147748608, result=result@entry=0x557dfa1b3d10, unit=unit@entry=0x557df9beb518, select_lex=select_lex@entry=0x557dfa1b2520) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:4745
#15 0x0000557df6cd424f in handle_select (thd=thd@entry=0x557df9be7988, lex=lex@entry=0x557df9beb458, result=result@entry=0x557dfa1b3d10, setup_tables_done_option=setup_tables_done_option@entry=0) at /home/midenok/src/mariadb/10.4/src/sql/sql_select.cc:448
#16 0x0000557df6c738f8 in execute_sqlcom_select (thd=thd@entry=0x557df9be7988, all_tables=0x557dfa1b2b10) at /home/midenok/src/mariadb/10.4/src/sql/sql_parse.cc:6446
#17 0x0000557df6c7c4c4 in mysql_execute_command (thd=thd@entry=0x557df9be7988) at /home/midenok/src/mariadb/10.4/src/sql/sql_parse.cc:3965
#18 0x0000557df6c81f0b in mysql_parse (thd=0x557df9be7988, rawbuf=<optimized out>, length=<optimized out>, parser_state=<optimized out>, is_com_multi=<optimized out>, is_next_command=<optimized out>) at /home/midenok/src/mariadb/10.4/src/sql/sql_parse.cc:7992
```
```
grep -E 'JOIN::exec|do_select|sub_select|join_init_read_record|st_join_table::sort_table|create_sort_index|find_all_keys|handler::ha_rnd_next|general_fetch|row_search_mvcc|rec_get_offsets_func'
```
### Good
```
objdump -xC `which mysqld`|grep -E 'JOIN::exec|do_select|sub_select|join_init_read_record|st_join_table::sort_table|create_sort_index|find_all_keys|handler::ha_rnd_next|general_fetch|row_search_mvcc|rec_get_offsets_func'
```
```
00000000009463b0 l     F .text  0000000000000bac              rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)
0000000000989410 l     F .text  00000000000030f5              row_search_mvcc(unsigned char*, page_cur_mode_t, row_prebuilt_t*, unsigned long, unsigned long)
0000000000489cc0 g     F .text  000000000000008d              LEX::add_primary_to_query_expression_body(st_select_lex_unit*, st_select_lex*, sub_select_type, bool, bool)
00000000008a4670 g     F .text  00000000000006d8              .hidden thr_find_all_keys
00000000004d0210 g     F .text  0000000000000055              st_join_table::sort_table()
00000000004d0270 g     F .text  0000000000000112              join_init_read_record(st_join_table*)
00000000008567d0 g     F .text  00000000000006c5              .hidden _ma_thr_find_all_keys
0000000000489bd0 g     F .text  00000000000000e5              LEX::parsed_select_expr_cont(st_select_lex_unit*, st_select_lex*, sub_select_type, bool, bool)
00000000004f4fd0 g     F .text  0000000000000077              JOIN::exec()
00000000004c7ab0 g     F .text  000000000000020d              sub_select_cache(JOIN*, st_join_table*, bool)
00000000004f4140 g     F .text  0000000000000e82              JOIN::exec_inner()
00000000008bbea0 g     F .text  00000000000002f7              .hidden ha_innobase::general_fetch(unsigned char*, unsigned int, unsigned int)
000000000047cfb0 g     F .text  000000000000005c              LEX::check_automatic_up(sub_select_type)
00000000004cfea0 g     F .text  000000000000036e              create_sort_index(THD*, JOIN*, st_join_table*, Filesort*)
0000000000489710 g     F .text  000000000000008b              LEX::add_primary_to_query_expression_body_ext_parens(st_select_lex_unit*, st_select_lex*, sub_select_type, bool)
00000000004895e0 g     F .text  0000000000000124              LEX::parsed_select_expr_start(st_select_lex*, st_select_lex*, sub_select_type, bool)
00000000004d6ac0 g     F .text  0000000000000076              sub_select_postjoin_aggr(JOIN*, st_join_table*, bool)
00000000004c7580 g     F .text  0000000000000522              sub_select(JOIN*, st_join_table*, bool)
0000000000671450 g     F .text  00000000000001d3              handler::ha_rnd_next(unsigned char*)
```
### Bad
```
00000000009463a0 l     F .text  0000000000000bac              rec_get_offsets_func(unsigned char const*, dict_index_t const*, unsigned short*, unsigned long, unsigned long, mem_block_info_t**)
00000000009890c0 l     F .text  00000000000030e5              row_search_mvcc(unsigned char*, page_cur_mode_t, row_prebuilt_t*, unsigned long, unsigned long)
0000000000489d50 g     F .text  000000000000008d              LEX::add_primary_to_query_expression_body(st_select_lex_unit*, st_select_lex*, sub_select_type, bool, bool)
00000000008a44d0 g     F .text  00000000000006d8              .hidden thr_find_all_keys
00000000004d0330 g     F .text  0000000000000055              st_join_table::sort_table()
00000000004d0390 g     F .text  0000000000000112              join_init_read_record(st_join_table*)
00000000008566f0 g     F .text  00000000000006c5              .hidden _ma_thr_find_all_keys
0000000000489c60 g     F .text  00000000000000e5              LEX::parsed_select_expr_cont(st_select_lex_unit*, st_select_lex*, sub_select_type, bool, bool)
00000000004f50f0 g     F .text  0000000000000077              JOIN::exec()
00000000004c7bd0 g     F .text  000000000000020d              sub_select_cache(JOIN*, st_join_table*, bool)
00000000004f4260 g     F .text  0000000000000e82              JOIN::exec_inner()
00000000008bbcf0 g     F .text  00000000000002f7              .hidden ha_innobase::general_fetch(unsigned char*, unsigned int, unsigned int)
000000000047d040 g     F .text  000000000000005c              LEX::check_automatic_up(sub_select_type)
00000000004cffc0 g     F .text  000000000000036e              create_sort_index(THD*, JOIN*, st_join_table*, Filesort*)
00000000004897a0 g     F .text  000000000000008b              LEX::add_primary_to_query_expression_body_ext_parens(st_select_lex_unit*, st_select_lex*, sub_select_type, bool)
0000000000489670 g     F .text  0000000000000124              LEX::parsed_select_expr_start(st_select_lex*, st_select_lex*, sub_select_type, bool)
00000000004d6be0 g     F .text  0000000000000076              sub_select_postjoin_aggr(JOIN*, st_join_table*, bool)
00000000004c76a0 g     F .text  0000000000000522              sub_select(JOIN*, st_join_table*, bool)
00000000006714d0 g     F .text  00000000000001d3              handler::ha_rnd_next(unsigned char*)
```
### Conclusion
Offsets almost same. Nothing wrong with binary linking?

**Comment by midenok** [comment]
### Good
```
mp -q
! Started: 111172
* Q0: real: 4.97  min: 4.97  max: 4.97
! Stopped: 111172
* Server dirty stats:
rfaults: 60839  fso: 4368  rss_max: 181652  cpu: 66  sys: 0.33  usr: 4.90  real: 7.90  ctx0: 5  ctx1: 545
```

**Comment by midenok** [comment]
### Produce script from CMake output
```
(echo '#!/bin/bash'; echo "set -xe"; cat bad.log|sed -rne '/^\[/ {s/^\[.+\] //;s|/home/midenok/src/mariadb/10.4c|$HOME|g;s/^/(/;s/$/)/;p}') > bad.sh; chmod +x bad.sh
```
### Check text section alignment
```
$ objdump -h `which mysqld`|grep -E '.text|Algn'
Idx Name          Size      VMA               LMA               File off  Algn
 15 .text         010750c7  0000000000d0ec80  0000000000d0ec80  00d0dc80  2**6
```
