### ISSUE TITLE
MDEV-19814 Server crash in row_upd_del_mark_clust_rec or Assertion `update->n_fields < ulint(table->n_cols + table->n_v_cols)' failed in upd_node_t::make_versioned_helper

### ISSUE THREAD

**Issue by midenok** [midenok/mariadb#55]
### Reproduce
```sql
create or replace table t1 (f varchar(1), row_start bigint unsigned as row start, row_end bigint unsigned as row end, period for system_time(row_start,row_end)) with system versioning;
insert into t1 (f) values ('a'),('b'),('c'),('d'),('e'),('f'),('g'),('h');
delete from t1;
delete history from t1;
```
One-liner:
```sql
create or replace table t1 (f varchar(1), row_start bigint unsigned as row start, row_end bigint unsigned as row end, period for system_time(row_start,row_end)) with system versioning engine=innodb; insert into t1 (f) values ('a'),('b'),('c'),('d'),('e'),('f'),('g'),('h'); delete from t1; delete history from t1;
```
### Result
```

**Comment by midenok** [comment]
### 1. `upd_t` initialized
```c++
#0  __memset_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:204
#1  0x00000000007bccaa in __asan_memset ()
#2  0x00000000021bcd84 in mem_heap_zalloc (heap=0x6210000add00, n=336) at /home/midenok/src/mariadb/trunk/src/storage/innobase/include/mem0mem.ic:170
#3  0x00000000021c5c42 in upd_create (n=6, heap=0x6210000add00) at /home/midenok/src/mariadb/trunk/src/storage/innobase/include/row0upd.ic:46
#4  0x00000000021c57da in row_create_update_node_for_mysql (table=0x619000117c08, heap=0x6210000add00) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0mysql.cc:1640
#5  0x00000000021c5dc3 in row_get_prebuilt_update_vector (prebuilt=0x6210000add88) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0mysql.cc:1672
#6  0x0000000001d86895 in ha_innobase::delete_row (this=0x61c00002d0a8, record=0x61900011a3b8 "\376\001a\215\022") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:8990
#7  0x0000000001645228 in handler::ha_delete_row (this=0x61c00002d0a8, buf=0x61900011a3b8 "\376\001a\215\022") at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:6790
#8  0x0000000001bf609a in TABLE::delete_row (this=0x62000003e088) at /home/midenok/src/mariadb/trunk/src/sql/sql_delete.cc:289
#9  0x0000000001be9060 in mysql_delete (thd=0x62b0000af208, table_list=0x62b0000b6320, conds=0x62b0000b6ef0, order_list=0x62b0000b3bb8, limit=18446744073709551615, options=0, result=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_delete.cc:801
#10 0x0000000000c047c5 in mysql_execute_command (thd=0x62b0000af208) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:4708
#11 0x0000000000beb225 in mysql_parse (thd=0x62b0000af208, rawbuf=0x62b0000b6228 "delete from t1", length=14, parser_state=0x7fffd03d2f60, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7892
```
### 2. `upd_t::n_fields` assigned 6
```c++
#0  upd_create (n=6, heap=0x6210000add00) at /home/midenok/src/mariadb/trunk/src/storage/innobase/include/row0upd.ic:50
```
#### frame 1
```c++
1640            node->update = upd_create(dict_table_get_n_cols(table)
1641                                      + dict_table_get_n_v_cols(table), heap);
```
### 3. `upd_t::n_fields` assigned 0
```c++
#0  upd_node_t::make_versioned_delete (this=0x6210000ae8c0, trx=0x7fffe9582a38) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0upd.cc:3512
#1  0x00000000021c7283 in row_update_for_mysql (prebuilt=0x6210000add88) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0mysql.cc:1877
#2  0x0000000001d86c2c in ha_innobase::delete_row (this=0x61c00002d0a8, record=0x61900011a3b8 "\376\001a\215\022") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:9002
```
#### frame 1
```c++
3506    /** Only set row_end = CURRENT_TIMESTAMP/trx->id.
3507    Do not touch other fields at all.
3508    @param[in]      trx     transaction */
3509    void upd_node_t::make_versioned_delete(const trx_t* trx)
3510    {
3511            update->n_fields = 0;
3512            is_delete = VERSIONED_DELETE;
3513            make_versioned_helper(trx, table->vers_end);
3514    }
```
### 4. Assertion passed, `upd_t::n_fields` incremented to 1
```c++
#0  upd_node_t::make_versioned_helper (this=0x6210000ae8c0, trx=0x7fffe9582a38, idx=2) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0upd.cc:3483
#1  0x00000000022b09f6 in upd_node_t::make_versioned_delete (this=0x6210000ae8c0, trx=0x7fffe9582a38) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0upd.cc:3513
#2  0x00000000021c7283 in row_update_for_mysql (prebuilt=0x6210000add88) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0mysql.cc:1877
#3  0x0000000001d86c2c in ha_innobase::delete_row (this=0x61c00002d0a8, record=0x61900011a3b8 "\376\001a\215\022") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:9002
```
### 5. records are deleted in loop
3. and 4. repeats.
### 6. `upd_t::n_fields` incremented to 2
```c++
#0  upd_node_t::make_versioned_helper (this=0x6210000ae8c0, trx=0x7fffe9582a38, idx=1) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0upd.cc:3483
#1  0x00000000022b0823 in upd_node_t::make_versioned_update (this=0x6210000ae8c0, trx=0x7fffe9582a38) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0upd.cc:3503
#2  0x00000000021c7301 in row_update_for_mysql (prebuilt=0x6210000add88) at /home/midenok/src/mariadb/trunk/src/storage/innobase/row/row0mysql.cc:1879
#3  0x0000000001d86c2c in ha_innobase::delete_row (this=0x61c00002d0a8, record=0x6190000ea1b8 "\376\001a\235\022") at /home/midenok/src/mariadb/trunk/src/storage/innobase/handler/ha_innodb.cc:9002
#4  0x0000000001645228 in handler::ha_delete_row (this=0x61c00002d0a8, buf=0x6190000ea1b8 "\376\001a\235\022") at /home/midenok/src/mariadb/trunk/src/sql/handler.cc:6790
#5  0x0000000001bf609a in TABLE::delete_row (this=0x62000003e088) at /home/midenok/src/mariadb/trunk/src/sql/sql_delete.cc:289
#6  0x0000000001be9060 in mysql_delete (thd=0x62b0000af208, table_list=0x62b0000b6330, conds=0x62b0000b6f00, order_list=0x62b0000b3bb8, limit=18446744073709551615, options=0, result=0x0) at /home/midenok/src/mariadb/trunk/src/sql/sql_delete.cc:801
#7  0x0000000000c047c5 in mysql_execute_command (thd=0x62b0000af208) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:4708
#8  0x0000000000beb225 in mysql_parse (thd=0x62b0000af208, rawbuf=0x62b0000b6228 "delete history from t1", length=22, parser_state=0x7fffd03f4f60, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/trunk/src/sql/sql_parse.cc:7892
```
### 7. `upd_t::n_fields` incremented to 3, 4, 5 and 6
6. repeats in DELETE HISTORY loop.
### Cause
`upd_node_t::make_versioned_update()` is called on non-versioned operation. DELETE HISTORY must behave like plain DELETE.
